Adding util(process) module
goravsingal/hubble pull request #59
Opened 2020-10-21 08:18 UTC by goravsingal

Adding util(process) module

2020-10-21 10:27 UTC, devagupt requested changes

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +        filter_rules:
no explanation in documentation about this parameter

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +All functions in this module are meant to be used in chaining.
Does this mean that we should block all calls from audit module ?

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +        AuditCheckValidationError: For any validation error
Typo in error name

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +    log.debug('Module: service Start validating params for check-id: {0}'.format(block_id))
typo in module name

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +        starting_seq: [3, 4]
function param is not provided in this block which is mandatory param

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +    log.debug('Executing stat module for id: {0}'.format(block_id))
typo in module name

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +
please add get_filtered_params_to_log function in this module

2020-10-21 10:27 UTC, devagupt commented on hubblestack/extmods/hubble_mods/util.py
> +    Given a list list, return the item found at ``index``.
typo fix

2020-10-22 07:48 UTC, goravsingal commented on hubblestack/extmods/hubble_mods/util.py
> +        filter_rules:
Added detailed doc

2020-10-26 03:53 UTC, devagupt approved these changes

2020-10-26 03:53 UTC, merged